# Generated by Django 4.2.5 on 2023-09-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
