# Generated by Django 4.2.5 on 2024-02-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='charter',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
