# Generated by Django 4.2.5 on 2024-02-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_charter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='charter',
        ),
    ]
