# Generated by Django 5.0.3 on 2024-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_charter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.JSONField(default={}),
        ),
    ]
