# Generated by Django 4.2.3 on 2023-09-14 19:11

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.FileField(upload_to='images/categories/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.FileField(upload_to='images/categories/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3, unique=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(31)])),
                ('image', models.FileField(upload_to='images/sizes/')),
            ],
        ),
        migrations.CreateModel(
            name='WheelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3, unique=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(31)])),
                ('image', models.FileField(upload_to='images/sizes/')),
            ],
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.CharField(max_length=30, unique=True)),
                ('image', models.FileField(upload_to=app.models.products_filename_wrapper)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
                ('characteristics', models.ManyToManyField(blank=True, to='app.characteristics')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.CharField(max_length=30, unique=True)),
                ('image', models.FileField(upload_to=app.models.products_filename_wrapper)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
                ('characteristics', models.ManyToManyField(blank=True, to='app.characteristics')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.CharField(max_length=30, unique=True)),
                ('image', models.FileField(upload_to=app.models.products_filename_wrapper)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
                ('characteristics', models.ManyToManyField(blank=True, to='app.characteristics')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.color')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.framesize')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.wheelsize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
