# Generated by Django 5.0.2 on 2024-02-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subcategory_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesandother',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
