# Generated by Django 3.2.21 on 2023-09-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230927_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitenavigation',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='sitenavigation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sitenavigation',
            name='link',
        ),
    ]
