# Generated by Django 4.2.5 on 2023-09-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230927_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helmet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Bicycle',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='FrameSize',
        ),
        migrations.DeleteModel(
            name='Helmet',
        ),
        migrations.DeleteModel(
            name='Lighting',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='WheelSize',
        ),
    ]
