# Generated by Django 4.2.6 on 2023-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('acsessories', models.ManyToManyField(to='products.accessorie')),
                ('bicycles', models.ManyToManyField(to='products.bicycle')),
                ('components', models.ManyToManyField(to='products.component')),
            ],
        ),
    ]
