# Generated by Django 5.0.3 on 2024-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='info',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (3, 'On way'), (4, 'Delivered')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=models.JSONField(default=dict, verbose_name='OrderInfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner_surname',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
