# Generated by Django 5.0.3 on 2024-03-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_info_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
