# Generated by Django 5.0.3 on 2024-03-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_info',
            field=models.JSONField(default=[], verbose_name='OrderInfo'),
        ),
    ]
