# Generated by Django 5.0.3 on 2024-03-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_info',
            field=models.JSONField(default=list, verbose_name='OrderInfo'),
        ),
    ]
