# Generated by Django 5.0.2 on 2024-03-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorie',
            name='slug',
            field=models.CharField(auto_created=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='slug',
            field=models.CharField(auto_created=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.CharField(auto_created=True, editable=False, max_length=50),
        ),
    ]
