# Generated by Django 4.2.5 on 2023-10-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='characteristics',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.AddField(
            model_name='characteristicdescription',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.characteristictitle'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='characteristics',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='products.characteristicdescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamlet',
            name='characteristics',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='products.characteristicdescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighting',
            name='characteristics',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='products.characteristicdescription'),
            preserve_default=False,
        ),
    ]
