# Generated by Django 4.2.5 on 2023-09-30 02:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_manufacturer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=products.models.products_filename_wrapper)),
                ('article', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='framesize',
            name='image',
        ),
        migrations.RemoveField(
            model_name='wheelsize',
            name='image',
        ),
        migrations.AddField(
            model_name='color',
            name='first_color',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='second_color',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framesize',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=7, unique=True, validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='wheelsize',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=7, unique=True, validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='galery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.galery'),
        ),
        migrations.AddField(
            model_name='helmet',
            name='galery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.galery'),
        ),
        migrations.AddField(
            model_name='lighting',
            name='galery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.galery'),
        ),
    ]
