# Generated by Django 4.2.6 on 2023-10-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_characteristicdescription_characteristictitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristicdescription',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.characteristictitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristicdescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characteristictitle',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
