# Generated by Django 4.2.6 on 2023-10-12 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_characteristicdescription_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelsize',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=10, unique=True, validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
