# Generated by Django 4.2.5 on 2023-09-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_galery_remove_color_name_remove_framesize_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='first_color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='color',
            name='second_color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
