# Generated by Django 4.2.5 on 2023-09-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_color_first_color_alter_color_second_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='galery',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='galery',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='galery',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='galery',
            field=models.ManyToManyField(blank=True, to='products.galery'),
        ),
        migrations.AddField(
            model_name='helmet',
            name='galery',
            field=models.ManyToManyField(blank=True, to='products.galery'),
        ),
        migrations.AddField(
            model_name='lighting',
            name='galery',
            field=models.ManyToManyField(blank=True, to='products.galery'),
        ),
    ]
