# Generated by Django 4.2.6 on 2023-10-12 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('products', '0004_alter_wheelsize_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('label', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.CharField(max_length=30, unique=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.FileField(blank=True, upload_to=products.models.products_filename_wrapper)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('label', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('article', models.CharField(max_length=30, unique=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.FileField(blank=True, upload_to=products.models.products_filename_wrapper)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(auto_created=True, editable=False, max_length=30)),
                ('image', models.FileField(blank=True, upload_to=products.models.products_filename_wrapper)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.component')),
            ],
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='subcategory',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='first_color',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='color',
            name='second_color',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='model',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='rgb',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='suspension_travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.suspensiontravel'),
        ),
        migrations.RenameModel(
            old_name='HamletGalery',
            new_name='AccessorieGalery',
        ),
        migrations.DeleteModel(
            name='CharacteristicDescription',
        ),
        migrations.DeleteModel(
            name='CharacteristicTitle',
        ),
        migrations.DeleteModel(
            name='Hamlet',
        ),
        migrations.DeleteModel(
            name='Lighting',
        ),
        migrations.AddField(
            model_name='component',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.color'),
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.manufacturer'),
        ),
        migrations.AddField(
            model_name='component',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.size'),
        ),
        migrations.AddField(
            model_name='component',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subcategory'),
        ),
        migrations.AddField(
            model_name='component',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.weight'),
        ),
        migrations.AddField(
            model_name='accessorie',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.color'),
        ),
        migrations.AddField(
            model_name='accessorie',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.manufacturer'),
        ),
        migrations.AddField(
            model_name='accessorie',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.size'),
        ),
        migrations.AddField(
            model_name='accessorie',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subcategory'),
        ),
        migrations.AddField(
            model_name='accessorie',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.weight'),
        ),
        migrations.AlterField(
            model_name='accessoriegalery',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.accessorie'),
        ),
    ]
