# Generated by Django 4.2.5 on 2023-09-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_bicycle_galery_remove_helmet_galery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='second_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
