# Generated by Django 4.2.5 on 2023-09-30 02:26

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_color_second_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='galery',
        ),
        migrations.RemoveField(
            model_name='galery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='galery',
        ),
        migrations.RemoveField(
            model_name='lighting',
            name='galery',
        ),
        migrations.AddField(
            model_name='galery',
            name='images',
            field=models.FileField(blank=True, upload_to=products.models.products_filename_wrapper),
        ),
        migrations.AddField(
            model_name='galery',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.bicycle'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image',
            field=models.FileField(blank=True, upload_to=products.models.products_filename_wrapper),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='image',
            field=models.FileField(blank=True, upload_to=products.models.products_filename_wrapper),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='image',
            field=models.FileField(blank=True, upload_to=products.models.products_filename_wrapper),
        ),
    ]
