# Generated by Django 4.2.6 on 2023-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_characteristic_characteristicvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorie',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='characteristics',
        ),
        migrations.AlterField(
            model_name='color',
            name='rgb',
            field=models.CharField(max_length=13),
        ),
        migrations.RemoveField(
            model_name='component',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='accessorie',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='products.characteristicvalue'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='products.characteristicvalue'),
        ),
        migrations.AddField(
            model_name='component',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='products.characteristicvalue'),
        ),
    ]
