# Generated by Django 4.2.5 on 2023-09-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_bicycle_galery_remove_galery_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galery',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='galery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.bicycle'),
        ),
    ]
