# Generated by Django 4.2.6 on 2023-10-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_accessorie_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='color',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='color',
            field=models.ManyToManyField(to='products.color'),
        ),
    ]
