# Generated by Django 4.2.5 on 2023-09-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_images_galery_image_alter_galery_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galery',
        ),
    ]
