# Generated by Django 4.2.5 on 2023-09-30 02:32

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_galery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to=products.models.products_filename_wrapper)),
            ],
        ),
    ]
