# Generated by Django 4.2.5 on 2023-09-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_galery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.bicycle'),
            preserve_default=False,
        ),
    ]
