# Generated by Django 4.2.5 on 2023-09-30 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_galery_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='product',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='galery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.galery'),
        ),
        migrations.AddField(
            model_name='helmet',
            name='galery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.galery'),
        ),
        migrations.AddField(
            model_name='lighting',
            name='galery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.galery'),
        ),
    ]
