# Generated by Django 4.2.5 on 2023-09-30 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_bicyclegalery_remove_bicycle_galery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicyclegalery',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.bicycle'),
        ),
    ]
